language: python
python:
  - "3.6"
install:
  - pip install -e .[dev]
script:
  - python setup.py test

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
